name: EKS
on: [push]

jobs:
  eks-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: "arn:aws:iam::590183844603:role/AmazonEKSClusterPolicy"
          # role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 1200
          # role-session-name: RoleSessionName
        
      # - name: Terraform Apply
      #   uses: dflook/terraform-apply@v1.44.0
      #   with:
      #     auto_approve: true
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        
      - name: Terraform Apply
        run: |
          terraform init
          terraform apply --auto-approve

  install-nginx:
    needs: [eks-infrastructure]
    runs-on: ubuntu-latest
    defaults:
      run:    
        working-directory: ./kubernetes
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.2/deploy/static/provider/aws/deploy.yaml
    
  api-objects:
    needs: [eks-infrastructure]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kubernetes 
    steps: 
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Terraform Apply Resources
          run: |
            terraform init
            terraform apply --auto-approve --var postgres_username=${{ secrets.POSTGRES_USERNAME }} --var postgres_password=${{ secrets.POSTGRES_PASSWORD }}
